id: I0AB5CAA5
legacy_id: P004460
ocr_import_info:
  bdrc_scan_id: W1KG4191
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T14:41:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:23:13.151584+00:00'
last_modified: 2022-08-31 23:23:51.404344
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4191
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4191
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། སྒྲུབ་བརྒྱུད་ཉི་མ།
  author: ཁམས་སྤྲུལ ༠༥་སྒྲུབ་བརྒྱུད་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.6870401555504025
  ocr_word_median_confidence_index: 0.7400000095367432
quality: null
bases:
  I1PD96704:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD96704
      total_pages: 542
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD96704.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7752209179135016
    legacy_id: v002
  I1PD96705:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD96705
      total_pages: 576
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1PD96705.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8159631645733512
    legacy_id: v003
  I1PD96703:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD96703
      total_pages: 584
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD96703.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5756986709443385
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
