id: I0AB5CAA5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:45:35+00:00'
last_modified: '2022-06-08T01:14:33.695766+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4191
  title: གསུང་འབུམ། སྒྲུབ་བརྒྱུད་ཉི་མ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4533':
      image_group_id: I1PD96703
      title: ''
      total_pages: 584
      order: 1
      base_file: 4533.txt
    98BE:
      image_group_id: I1PD96704
      title: ''
      total_pages: 542
      order: 2
      base_file: 98BE.txt
    D14A:
      image_group_id: I1PD96705
      title: ''
      total_pages: 576
      order: 3
      base_file: D14A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
