id: P004460
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG4191
  title: གསུང་འབུམ། སྒྲུབ་བརྒྱུད་ཉི་མ
  author: ''
  volumes:
    d352d86c732f44818e47ebb449e29b02:
      image_group_id: I1PD96703
      title: ''
      volume_number: 1
      total_pages: 584
      base_file: v001.txt
    c92328485a924852868f37c48da4ee5d:
      image_group_id: I1PD96704
      title: ''
      volume_number: 2
      total_pages: 542
      base_file: v002.txt
    0f9bbb89bd814786845701703c4c90f5:
      image_group_id: I1PD96705
      title: ''
      volume_number: 3
      total_pages: 576
      base_file: v003.txt
